"""add time creation column

Revision ID: e9b37b524d49
Revises: 1a920619b476
Create Date: 2020-10-15 14:27:54.453579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e9b37b524d49'
down_revision = '1a920619b476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('team', sa.Column('time', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'time')
    op.drop_column('members', 'time')
    # ### end Alembic commands ###
